version: '3.8'

services:
  web:
    build: ./server/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./server/web:/usr/src/app
      - ./server/uploads:/usr/src/app/uploads
      - ./server/tests:/usr/src/app/tests
    ports:
      - 5000:5000
    depends_on:
      - db
      - redis
    environment:
       - FLASK_APP=project/__init__.py
       - FLASK_ENV=development
       - SECRET_KEY=9OLWxND4o83j4Kty567pO
       - FLASK_RUN_PORT=5000
       - DATABASE_URL=postgresql://pstgr_user:pstgr_pass@db:5432/pstgr_db
       - REDIS_URL=redis://redis:6379
       - APP_FOLDER=/usr/src/app
      #Used for entrypoint.sh while waiting postgre container is ready
       - SQL_HOST=db
       - SQL_PORT=5432
       - DATABASE=postgres 

  db:
    build: ./server/db
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=pstgr_user
      - POSTGRES_PASSWORD=pstgr_pass
      - POSTGRES_DB=pstgr_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres_data:
  redis_data:
